name: Go Test and Simulate Deployment Pipeline

on:
  push:
    paths:
      - 'cloud/l_3/be/**'  # Trigger on changes in this folder
  pull_request:
    paths:
      - 'cloud/l_3/be/**'  # Trigger on pull requests affecting this folder

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21', '1.22']  # List of Go versions to test on

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run Tests
        working-directory: cloud/l_3/be
        run: |
          go test ./... -v

      - name: Simulate Deployment
        if: success()
        run: echo "Deployed"
